# this shell script is very odd because find only lets {} be at the end of the exec command OR only lets it be used once
# $1 = data path
# $2 = starting path for the output files generated by this command
# $3 = relative path specifically that we are working on
chevron -d $1 $3 > $2/$3
